# Generated by Django 6.0.4 on 2026-04-21 19:10

import apps.registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان داخلی برای مدیریت', max_length=200, verbose_name='عنوان')),
                ('message_type', models.CharField(choices=[('text', 'پیام متنی'), ('file', 'فایل / سند'), ('photo', 'تصویر'), ('link', 'لینک')], default='text', max_length=20, verbose_name='نوع پیام')),
                ('text_content', models.TextField(blank=True, help_text='از Markdown پشتیبانی می\u200cشود', verbose_name='متن پیام')),
                ('file', models.FileField(blank=True, null=True, upload_to='scheduled_messages/', verbose_name='فایل')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='scheduled_messages/photos/', verbose_name='تصویر')),
                ('link_url', models.URLField(blank=True, verbose_name='آدرس لینک')),
                ('link_text', models.CharField(blank=True, max_length=200, verbose_name='متن دکمه لینک')),
                ('scheduled_time', models.DateTimeField(help_text='پیام در این زمان به همه کاربران ثبت\u200cنام شده ارسال می\u200cشود', verbose_name='زمان ارسال')),
                ('is_sent', models.BooleanField(db_index=True, default=False, verbose_name='ارسال شده')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال واقعی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پیام زمان\u200cبندی شده',
                'verbose_name_plural': 'پیام\u200cهای زمان\u200cبندی شده',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='فقط برای مدیریت داخلی — کاربر نمی\u200cبیند', max_length=200, verbose_name='عنوان (داخلی)')),
                ('text', models.TextField(help_text='از Markdown پشتیبانی می\u200cشود (*bold*, _italic_, etc.)', verbose_name='متن خوش\u200cآمدگویی')),
                ('is_active', models.BooleanField(default=True, help_text='فقط یک پیام می\u200cتواند فعال باشد', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پیام خوش\u200cآمدگویی',
                'verbose_name_plural': 'پیام\u200cهای خوش\u200cآمدگویی',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='finalmessage',
            options={'ordering': ['order', '-updated_at'], 'verbose_name': 'پیام نهایی', 'verbose_name_plural': 'پیام\u200cهای نهایی'},
        ),
        migrations.AddField(
            model_name='finalmessage',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text='پیام\u200cها بر اساس این عدد به ترتیب ارسال می\u200cشوند', verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='finalmessage',
            name='file',
            field=models.FileField(blank=True, help_text='فایل ارسالی به کاربر پس از ثبت\u200cنام', null=True, upload_to=apps.registration.models.final_message_upload_to, verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='finalmessage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='فقط یک پیام می\u200cتواند فعال باشد', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='finalmessage',
            name='link_text',
            field=models.CharField(blank=True, help_text='متن دکمه inline — اگر خالی باشد لینک به صورت متن ارسال می\u200cشود', max_length=200, verbose_name='متن دکمه لینک'),
        ),
        migrations.AlterField(
            model_name='finalmessage',
            name='link_url',
            field=models.URLField(blank=True, help_text='مثال: https://example.com', verbose_name='آدرس لینک'),
        ),
        migrations.AlterField(
            model_name='finalmessage',
            name='text_content',
            field=models.TextField(blank=True, help_text='از Markdown پشتیبانی می\u200cشود (*bold*, _italic_, etc.)', verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='finalmessage',
            name='title',
            field=models.CharField(help_text='فقط برای مدیریت داخلی — کاربر نمی\u200cبیند', max_length=200, verbose_name='عنوان (داخلی)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, help_text='برای نوع "انتخابی": هر گزینه در یک خط. مثال:\nگزینه ۱\nگزینه ۲', null=True, verbose_name='گزینه\u200cها'),
        ),
        migrations.AlterField(
            model_name='question',
            name='field_name',
            field=models.SlugField(help_text='شناسه یکتا برای ذخیره پاسخ (فقط حروف لاتین و آندرلاین)', max_length=100, unique=True, verbose_name='نام فیلد'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='متنی که برای کاربر ارسال می\u200cشود', verbose_name='متن سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='validation_hint',
            field=models.CharField(blank=True, help_text='در صورت ورود نامعتبر این پیام نشان داده می\u200cشود', max_length=300, verbose_name='راهنمای اعتبارسنجی'),
        ),
        migrations.AlterField(
            model_name='registrationsession',
            name='answers',
            field=models.JSONField(default=dict, help_text='JSON ذخیره\u200cسازی پاسخ\u200cهای کاربر', verbose_name='پاسخ\u200cها'),
        ),
    ]
