# Generated by Django 6.0.4 on 2026-04-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_scheduledmessage_send_to_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmessage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
